# Markdownlint configuration for MetaCategory
default: true
MD003: true
MD004: { style: asterisk }
MD007: { indent: 2 }
MD013: { line_length: 120, code_blocks: false, tables: false }
MD022: true
MD025: true
MD026: { punctuation: ".,;:!" }
MD029: { style: one }
MD040: true
MD041: false
MD046: false
MD047: true
