{-# OPTIONS --without-K #-}

-- | CanonicalRoadmap: Authoritative roadmap data
-- Auto-generated by scripts/merge_roadmaps.py
-- DO NOT EDIT MANUALLY - Run `make roadmap-merge` to regenerate

module Plan.CIM.CanonicalRoadmap where

open import Plan.CIM.RoadmapIndex using (RoadmapItem; CanonicalRoadmap)
open import Agda.Builtin.List using (List; []; _∷_)

-- Canonical Roadmap Items (Auto-generated by merge_roadmaps.py)
-- DO NOT EDIT MANUALLY

canonicalItems : List RoadmapItem
canonicalItems =
  -- | LOCAL-DEF-DICT: Implement Definition Dictionary adequacy module [status: done]
  record {
    id = "LOCAL-DEF-DICT"
    ; title = "Implement Definition Dictionary adequacy module"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Definitions/Dictionary.agda" ∷ [])
    ; tags = ("Definition" ∷ "Adequacy" ∷ [])
    ; dependsOn = []
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR: Introduce generic functor interface for protocol bundles [status: in-progress]
  record {
    id = "LOCAL-GENERIC-FUNCTOR"
    ; title = "Introduce generic functor interface for protocol bundles"
    ; status = "in-progress"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ "src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda" ∷ "src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda" ∷ "src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ "src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda" ∷ "src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ "src/agda/Infrastructure/Functor/Compose.agda" ∷ "src/agda/Core/PhaseCategoryWrapper.agda" ∷ [])
    ; tags = ("Functor" ∷ "Interface" ∷ [])
    ; dependsOn = ("LOCAL-DEF-DICT" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS: Complete generic functor interface laws and helpers [status: in-progress]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS"
    ; title = "Complete generic functor interface laws and helpers"
    ; status = "in-progress"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags = ("Functor" ∷ "Interface" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INTERFACE-CONVENIENCE-LAWS: Add convenience lemmas for map-id/compose congruence [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INTERFACE-CONVENIENCE-LAWS"
    ; title = "Add convenience lemmas for map-id/compose congruence"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags = ("Functor" ∷ "Interface" ∷ "Law" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INTERFACE-DOCUMENTATION: Document interface laws and usage in code comments [status: not-started]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INTERFACE-DOCUMENTATION"
    ; title = "Document interface laws and usage in code comments"
    ; status = "not-started"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags = ("Functor" ∷ "Documentation" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR-DOCS" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION: Normalize existing functor instances onto shared interface [status: not-started]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION"
    ; title = "Normalize existing functor instances onto shared interface"
    ; status = "not-started"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda" ∷ "src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ "src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ "src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda" ∷ "src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-NORMALIZE-FUNCTION: Normalize FunctionCategory functor instance [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-FUNCTION"
    ; title = "Normalize FunctionCategory functor instance"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-NORMALIZE-FUNCPATH: Normalize FunctionPathCategory functor instance [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-FUNCPATH"
    ; title = "Normalize FunctionPathCategory functor instance"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-NORMALIZE-TRANSFORMATION: Normalize TransformationSystem functor instance [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-TRANSFORMATION"
    ; title = "Normalize TransformationSystem functor instance"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-NORMALIZE-PATHALGEBRA: Normalize PathAlgebra functor instance [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-PATHALGEBRA"
    ; title = "Normalize PathAlgebra functor instance"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-NORMALIZE-PHASE: Normalize PhaseCategory functor instance [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-PHASE"
    ; title = "Normalize PhaseCategory functor instance"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-NORMALIZE-AMBIGUITY: Normalize Ambiguity functor instance [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-AMBIGUITY"
    ; title = "Normalize Ambiguity functor instance"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY: Ensure adequacy kits follow standardized pattern [status: not-started]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY"
    ; title = "Ensure adequacy kits follow standardized pattern"
    ; status = "not-started"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-ADEQUACY-FUNCPATH: Confirm FunctionPath adequacy follows shared kit pattern [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-FUNCPATH"
    ; title = "Confirm FunctionPath adequacy follows shared kit pattern"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-ADEQUACY-TRANSFORMATION: Confirm TransformationSystem adequacy follows shared kit pattern [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-TRANSFORMATION"
    ; title = "Confirm TransformationSystem adequacy follows shared kit pattern"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-ADEQUACY-AMBIGUITY: Confirm Ambiguity adequacy follows shared kit pattern [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-AMBIGUITY"
    ; title = "Confirm Ambiguity adequacy follows shared kit pattern"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS: Align functor composition adapters with interface [status: not-started]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS"
    ; title = "Align functor composition adapters with interface"
    ; status = "not-started"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Compose.agda" ∷ "src/agda/Core/PhaseCategoryWrapper.agda" ∷ [])
    ; tags = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INTEROP-COMPOSE: Refine compose helper proofs for reuse [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INTEROP-COMPOSE"
    ; title = "Refine compose helper proofs for reuse"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Compose.agda" ∷ [])
    ; tags = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-INTEROP-PHASE-WRAPPER: Ensure PhaseCategoryWrapper matches interface helpers [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-INTEROP-PHASE-WRAPPER"
    ; title = "Ensure PhaseCategoryWrapper matches interface helpers"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Core/PhaseCategoryWrapper.agda" ∷ [])
    ; tags = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-EXAMPLES: Add regression examples exercising functor identity/compose [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-EXAMPLES"
    ; title = "Add regression examples exercising functor identity/compose"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Examples/FunctorComposition.agda" ∷ [])
    ; tags = ("Functor" ∷ "Example" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-DOCS: Document generic functor interface and upgrade guide [status: not-started]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-DOCS"
    ; title = "Document generic functor interface and upgrade guide"
    ; status = "not-started"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("ROADMAP.md" ∷ "docs/process" ∷ [])
    ; tags = ("Functor" ∷ "Documentation" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
  }
  ∷
  -- | DOCS-AGDA-DOCCOMMENT-PIPELINE: Extend module exporter to surface Agda doc comments [status: done]
  record {
    id = "DOCS-AGDA-DOCCOMMENT-PIPELINE"
    ; title = "Extend module exporter to surface Agda doc comments"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "Documentation"
    ; files = ("src/agda/Plan/CIM/ModuleExporter.agda" ∷ "docs/automation" ∷ [])
    ; tags = ("Documentation" ∷ "Pipeline" ∷ "Agda" ∷ [])
    ; dependsOn = []
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | DOCS-AGDA-DECL-DOCS: Export declaration docstrings (records/data) into docs [status: done]
  record {
    id = "DOCS-AGDA-DECL-DOCS"
    ; title = "Export declaration docstrings (records/data) into docs"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "Documentation"
    ; files = ("src/agda/Plan/CIM/ModuleExporter.agda" ∷ "docs/automation" ∷ [])
    ; tags = ("Documentation" ∷ "Pipeline" ∷ "Agda" ∷ [])
    ; dependsOn = ("DOCS-AGDA-DOCCOMMENT-PIPELINE" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | DOCS-AGDA-FIELD-DOCS: Export field/argument docstrings into docs [status: not-started]
  record {
    id = "DOCS-AGDA-FIELD-DOCS"
    ; title = "Export field/argument docstrings into docs"
    ; status = "not-started"
    ; category = "Infrastructure"
    ; source = "Documentation"
    ; files = ("src/agda/Plan/CIM/ModuleExporter.agda" ∷ "docs/automation" ∷ [])
    ; tags = ("Documentation" ∷ "Pipeline" ∷ "Agda" ∷ [])
    ; dependsOn = ("DOCS-AGDA-DECL-DOCS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | DOCS-AGDA-LINT: Add lint to enforce module-level docstrings [status: in-progress]
  record {
    id = "DOCS-AGDA-LINT"
    ; title = "Add lint to enforce module-level docstrings"
    ; status = "in-progress"
    ; category = "Infrastructure"
    ; source = "Documentation"
    ; files = ("scripts" ∷ "docs/automation" ∷ [])
    ; tags = ("Documentation" ∷ "Lint" ∷ "Agda" ∷ [])
    ; dependsOn = ("DOCS-AGDA-DOCCOMMENT-PIPELINE" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("DOCS-AGDA-DECL-DOCS" ∷ "DOCS-AGDA-FIELD-DOCS" ∷ [])
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-FUNCPATH-ADEQUACY: Add adequacy kit for FunctionPathCategory [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-FUNCPATH-ADEQUACY"
    ; title = "Add adequacy kit for FunctionPathCategory"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-TRANSFORMATION-ADEQUACY: Add adequacy hook for TransformationSystem functor [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-TRANSFORMATION-ADEQUACY"
    ; title = "Add adequacy hook for TransformationSystem functor"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-GENERIC-FUNCTOR-AMBIGUITY-ADEQUACY: Add adequacy hook for Ambiguity functor [status: done]
  record {
    id = "LOCAL-GENERIC-FUNCTOR-AMBIGUITY-ADEQUACY"
    ; title = "Add adequacy hook for Ambiguity functor"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = []
  }
  ∷
  -- | LOCAL-DEF-DICT-EXAMPLE: Add DefinitionDictionary adequacy example [status: done]
  record {
    id = "LOCAL-DEF-DICT-EXAMPLE"
    ; title = "Add DefinitionDictionary adequacy example"
    ; status = "done"
    ; category = "Infrastructure"
    ; source = "DefinitionDictionary"
    ; files = ("src/agda/Examples/DefinitionDictionaryAdequacy.agda" ∷ [])
    ; tags = ("Definition" ∷ "Example" ∷ [])
    ; dependsOn = ("LOCAL-DEF-DICT" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
  }
  ∷
  -- | GP-Gp400: GP400: The "Elasticity" of Meaning [status: not-started]
  record {
    id = "GP-Gp400"
    ; title = "GP400: The \"Elasticity\" of Meaning"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Corrections.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp400|Plan/CIM/IngestedRoadmaps/Corrections.agda" ∷ "ROADMAP-MD-1|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp500: GP500: Dimensional Relief [status: not-started]
  record {
    id = "GP-Gp500"
    ; title = "GP500: Dimensional Relief"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Corrections.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp500|Plan/CIM/IngestedRoadmaps/Corrections.agda" ∷ "ROADMAP-MD-2|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp501: GP501: The Topological Diagram (II) [status: not-started]
  record {
    id = "GP-Gp501"
    ; title = "GP501: The Topological Diagram (II)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Corrections.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp501|Plan/CIM/IngestedRoadmaps/Corrections.agda" ∷ "ROADMAP-MD-3|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp800: GP800: The Missing Morphisms [status: not-started]
  record {
    id = "GP-Gp800"
    ; title = "GP800: The Missing Morphisms"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp800|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-4|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp801: GP801: The Exterior Algebra of Meaning [status: not-started]
  record {
    id = "GP-Gp801"
    ; title = "GP801: The Exterior Algebra of Meaning"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp801|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-5|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp802: GP802: The Fundamental Group of the Grammar [status: not-started]
  record {
    id = "GP-Gp802"
    ; title = "GP802: The Fundamental Group of the Grammar"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp802|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-6|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp803: GP803: The Holographic Manifest (v11.0) [status: not-started]
  record {
    id = "GP-Gp803"
    ; title = "GP803: The Holographic Manifest (v11.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp803|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-7|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp804: GP804: The Missing Algebraic Topology [status: not-started]
  record {
    id = "GP-Gp804"
    ; title = "GP804: The Missing Algebraic Topology"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp804|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-8|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp805: GP805: The Discovery of "Dark Matter" [status: not-started]
  record {
    id = "GP-Gp805"
    ; title = "GP805: The Discovery of \"Dark Matter\""
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp805|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-9|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp806: GP806: The Geometry of Inference [status: not-started]
  record {
    id = "GP-Gp806"
    ; title = "GP806: The Geometry of Inference"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp806|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-10|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp807: GP807: The Logic of Exclusion [status: not-started]
  record {
    id = "GP-Gp807"
    ; title = "GP807: The Logic of Exclusion"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp807|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-11|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp808: GP808: The Arithmetic Foundation [status: not-started]
  record {
    id = "GP-Gp808"
    ; title = "GP808: The Arithmetic Foundation"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp808|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-12|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp809: GP809: The Logarithmic Isomorphism [status: not-started]
  record {
    id = "GP-Gp809"
    ; title = "GP809: The Logarithmic Isomorphism"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp809|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-13|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp810: GP810: The Spectral Manifest (v16.0) [status: not-started]
  record {
    id = "GP-Gp810"
    ; title = "GP810: The Spectral Manifest (v16.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp810|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-14|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp811: GP811: The Free Energy Principle [status: not-started]
  record {
    id = "GP-Gp811"
    ; title = "GP811: The Free Energy Principle"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp811|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-15|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp812: GP812: The Unified Manifest (v17.0) [status: not-started]
  record {
    id = "GP-Gp812"
    ; title = "GP812: The Unified Manifest (v17.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp812|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-16|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp813: GP813: The Missing Cohomology [status: not-started]
  record {
    id = "GP-Gp813"
    ; title = "GP813: The Missing Cohomology"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp813|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-17|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp814: GP814: The Cohomological Manifest (v18.0) [status: not-started]
  record {
    id = "GP-Gp814"
    ; title = "GP814: The Cohomological Manifest (v18.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp814|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-18|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp815: GP815: The Isomorphism of Process [status: not-started]
  record {
    id = "GP-Gp815"
    ; title = "GP815: The Isomorphism of Process"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp815|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-19|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp816: GP816: The Homotopy of Morphology [status: not-started]
  record {
    id = "GP-Gp816"
    ; title = "GP816: The Homotopy of Morphology"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp816|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-20|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp817: GP817: The Local-to-Global Principle [status: not-started]
  record {
    id = "GP-Gp817"
    ; title = "GP817: The Local-to-Global Principle"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp817|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-21|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp818: GP818: The Abelian Sheaf [status: not-started]
  record {
    id = "GP-Gp818"
    ; title = "GP818: The Abelian Sheaf"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp818|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-22|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp819: GP819: The Plus Construction [status: not-started]
  record {
    id = "GP-Gp819"
    ; title = "GP819: The Plus Construction"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp819|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-23|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp820: GP820: The Fractal Sheaf [status: not-started]
  record {
    id = "GP-Gp820"
    ; title = "GP820: The Fractal Sheaf"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp820|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-24|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp821: GP821: Recursive Self-Substitution [status: not-started]
  record {
    id = "GP-Gp821"
    ; title = "GP821: Recursive Self-Substitution"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp821|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-25|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp822: GP822: The Fractal Manifest (v22.0) [status: not-started]
  record {
    id = "GP-Gp822"
    ; title = "GP822: The Fractal Manifest (v22.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp822|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-26|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp823: GP823: The Descent to the Boolean Layer [status: not-started]
  record {
    id = "GP-Gp823"
    ; title = "GP823: The Descent to the Boolean Layer"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp823|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-27|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp824: GP824: The Quantum Manifold [status: not-started]
  record {
    id = "GP-Gp824"
    ; title = "GP824: The Quantum Manifold"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp824|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-28|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp825: GP825: Dynamic Gauge Symmetry [status: not-started]
  record {
    id = "GP-Gp825"
    ; title = "GP825: Dynamic Gauge Symmetry"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp825|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-29|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp826: GP826: The Self-Defining Manifold [status: not-started]
  record {
    id = "GP-Gp826"
    ; title = "GP826: The Self-Defining Manifold"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp826|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-30|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp827: GP827: The Cost of Gauge Coherence [status: not-started]
  record {
    id = "GP-Gp827"
    ; title = "GP827: The Cost of Gauge Coherence"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp827|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-31|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp828: GP828: The Recursive Clifford Lift [status: not-started]
  record {
    id = "GP-Gp828"
    ; title = "GP828: The Recursive Clifford Lift"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp828|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-32|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp829: GP829: The Fuzzy Boundary [status: not-started]
  record {
    id = "GP-Gp829"
    ; title = "GP829: The Fuzzy Boundary"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp829|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-33|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp830: GP830: The Latent Dynamic SPPF [status: not-started]
  record {
    id = "GP-Gp830"
    ; title = "GP830: The Latent Dynamic SPPF"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp830|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-34|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp831: GP831: The Causal Dimension [status: not-started]
  record {
    id = "GP-Gp831"
    ; title = "GP831: The Causal Dimension"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp831|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-35|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp832: GP832: The Self-Defining Manifest (v26.0) [status: not-started]
  record {
    id = "GP-Gp832"
    ; title = "GP832: The Self-Defining Manifest (v26.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Analysis.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp832|Plan/CIM/IngestedRoadmaps/Analysis.agda" ∷ "ROADMAP-MD-36|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp699: GP699: The Unified Topological Parser [status: not-started]
  record {
    id = "GP-Gp699"
    ; title = "GP699: The Unified Topological Parser"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp699|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-37|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp700: GP700: The Simplex vs. The Associahedron [status: not-started]
  record {
    id = "GP-Gp700"
    ; title = "GP700: The Simplex vs. The Associahedron"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp700|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-38|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp701: GP701: The Polytope Visualization [status: not-started]
  record {
    id = "GP-Gp701"
    ; title = "GP701: The Polytope Visualization"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp701|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-39|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp702: GP702: The Loday Realization [status: not-started]
  record {
    id = "GP-Gp702"
    ; title = "GP702: The Loday Realization"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp702|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-40|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp703: GP703: The Loday-Stasheff Manifest (v6.0) [status: not-started]
  record {
    id = "GP-Gp703"
    ; title = "GP703: The Loday-Stasheff Manifest (v6.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp703|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-41|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp704: GP704: The Geometry of Choice [status: not-started]
  record {
    id = "GP-Gp704"
    ; title = "GP704: The Geometry of Choice"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp704|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-42|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp705: GP705: The Polytope Storage [status: not-started]
  record {
    id = "GP-Gp705"
    ; title = "GP705: The Polytope Storage"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp705|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-43|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp706: GP706: The Operational Velocity [status: not-started]
  record {
    id = "GP-Gp706"
    ; title = "GP706: The Operational Velocity"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp706|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-44|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp707: GP707: The Knight's Move (Topological Surgery) [status: not-started]
  record {
    id = "GP-Gp707"
    ; title = "GP707: The Knight's Move (Topological Surgery)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp707|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-45|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp708: GP708: The Knight's Move Manifest (v8.0) [status: not-started]
  record {
    id = "GP-Gp708"
    ; title = "GP708: The Knight's Move Manifest (v8.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp708|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-46|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp709: GP709: The Operadic Tiling [status: not-started]
  record {
    id = "GP-Gp709"
    ; title = "GP709: The Operadic Tiling"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp709|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-47|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp710: GP710: The Operadic Manifest (v9.0) [status: not-started]
  record {
    id = "GP-Gp710"
    ; title = "GP710: The Operadic Manifest (v9.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp710|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-48|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp711: GP711: The Stable Interface Principle [status: not-started]
  record {
    id = "GP-Gp711"
    ; title = "GP711: The Stable Interface Principle"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp711|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-49|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp712: GP712: The Prediction of Topology [status: not-started]
  record {
    id = "GP-Gp712"
    ; title = "GP712: The Prediction of Topology"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp712|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-50|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp713: GP713: The Vacuum State [status: not-started]
  record {
    id = "GP-Gp713"
    ; title = "GP713: The Vacuum State"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp713|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-51|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp714: GP714: The Self-Defining Manifest (v26.0) [status: not-started]
  record {
    id = "GP-Gp714"
    ; title = "GP714: The Self-Defining Manifest (v26.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Polytopes.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp714|Plan/CIM/IngestedRoadmaps/Polytopes.agda" ∷ "ROADMAP-MD-52|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp01: GP01: The RotationalTransport Property [status: not-started]
  record {
    id = "GP-Gp01"
    ; title = "GP01: The RotationalTransport Property"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp01|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-53|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp010: GP010: The Deployment Substrate [status: not-started]
  record {
    id = "GP-Gp010"
    ; title = "GP010: The Deployment Substrate"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp010|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-54|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp02: GP02: The Geometric Alignment [status: not-started]
  record {
    id = "GP-Gp02"
    ; title = "GP02: The Geometric Alignment"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp02|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-55|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp03: GP03: The PackedNode Aggregation Logic [status: not-started]
  record {
    id = "GP-Gp03"
    ; title = "GP03: The PackedNode Aggregation Logic"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp03|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-56|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp04: GP04: The Topological Diagram (I) [status: not-started]
  record {
    id = "GP-Gp04"
    ; title = "GP04: The Topological Diagram (I)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp04|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-57|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp05: GP05: The Vectorized Earley Item [status: not-started]
  record {
    id = "GP-Gp05"
    ; title = "GP05: The Vectorized Earley Item"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp05|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-58|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp06: GP06: The Visualization Module [status: not-started]
  record {
    id = "GP-Gp06"
    ; title = "GP06: The Visualization Module"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp06|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-59|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp07: GP07: The Visual Semantics [status: not-started]
  record {
    id = "GP-Gp07"
    ; title = "GP07: The Visual Semantics"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp07|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-60|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp09: GP09: The Active Observer [status: not-started]
  record {
    id = "GP-Gp09"
    ; title = "GP09: The Active Observer"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp09|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-61|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp100: GP100: The Semantic Gating (I) [status: not-started]
  record {
    id = "GP-Gp100"
    ; title = "GP100: The Semantic Gating (I)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp100|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-62|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp101: GP101: The Semantic Gating (II) [status: not-started]
  record {
    id = "GP-Gp101"
    ; title = "GP101: The Semantic Gating (II)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp101|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-63|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp102: GP102: The Operational Integration [status: not-started]
  record {
    id = "GP-Gp102"
    ; title = "GP102: The Operational Integration"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp102|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-64|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp103: GP103: The Type-Theoretic Gate [status: not-started]
  record {
    id = "GP-Gp103"
    ; title = "GP103: The Type-Theoretic Gate"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp103|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-65|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp104: GP104: The Algebraic Structure of Ambiguity [status: not-started]
  record {
    id = "GP-Gp104"
    ; title = "GP104: The Algebraic Structure of Ambiguity"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp104|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-66|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp105: GP105: The "Fast Clock" Paradox [status: not-started]
  record {
    id = "GP-Gp105"
    ; title = "GP105: The \"Fast Clock\" Paradox"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp105|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-67|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp106: GP106: The Persistence of Potentiality [status: not-started]
  record {
    id = "GP-Gp106"
    ; title = "GP106: The Persistence of Potentiality"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp106|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-68|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp107: GP107: The Gödelian Manifest [status: not-started]
  record {
    id = "GP-Gp107"
    ; title = "GP107: The Gödelian Manifest"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp107|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-69|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp108: GP108: The "Homological Defect" [status: not-started]
  record {
    id = "GP-Gp108"
    ; title = "GP108: The \"Homological Defect\""
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp108|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-70|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp109: GP109: The Hebbian Drift [status: not-started]
  record {
    id = "GP-Gp109"
    ; title = "GP109: The Hebbian Drift"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp109|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-71|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp110: GP110: The Control Plane [status: not-started]
  record {
    id = "GP-Gp110"
    ; title = "GP110: The Control Plane"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp110|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-72|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp111: GP111: The Unified Manifest (v2.0) [status: not-started]
  record {
    id = "GP-Gp111"
    ; title = "GP111: The Unified Manifest (v2.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Foundation.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp111|Plan/CIM/IngestedRoadmaps/Foundation.agda" ∷ "ROADMAP-MD-73|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp200: GP200: The Geometry of Associativity [status: not-started]
  record {
    id = "GP-Gp200"
    ; title = "GP200: The Geometry of Associativity"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Geometry.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp200|Plan/CIM/IngestedRoadmaps/Geometry.agda" ∷ "ROADMAP-MD-74|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp201: GP201: The Non-Abelian Manifold [status: not-started]
  record {
    id = "GP-Gp201"
    ; title = "GP201: The Non-Abelian Manifold"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Geometry.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp201|Plan/CIM/IngestedRoadmaps/Geometry.agda" ∷ "ROADMAP-MD-75|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp300: GP300: The Fiber Bundle Architecture [status: not-started]
  record {
    id = "GP-Gp300"
    ; title = "GP300: The Fiber Bundle Architecture"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Geometry.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp300|Plan/CIM/IngestedRoadmaps/Geometry.agda" ∷ "ROADMAP-MD-76|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp302: GP302: The Operationalized Adjunction [status: not-started]
  record {
    id = "GP-Gp302"
    ; title = "GP302: The Operationalized Adjunction"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Geometry.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp302|Plan/CIM/IngestedRoadmaps/Geometry.agda" ∷ "ROADMAP-MD-77|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷
  -- | GP-Gp303: GP303: The Adjoint Manifest (v3.0) [status: not-started]
  record {
    id = "GP-Gp303"
    ; title = "GP303: The Adjoint Manifest (v3.0)"
    ; status = "not-started"
    ; category = "IngestedGP"
    ; source = "Plan/CIM/IngestedRoadmaps/Geometry.agda"
    ; files = ("src/agda/Plan/CIM/Implementation.agda" ∷ [])
    ; tags = ("GP" ∷ [])
    ; dependsOn = []
    ; provenance = ("GP-Gp303|Plan/CIM/IngestedRoadmaps/Geometry.agda" ∷ "ROADMAP-MD-78|ROADMAP.md" ∷ [])
    ; related = []
  }
  ∷ []
