{-# OPTIONS --without-K #-}

-- | PlanningKernel: bridge module to expose the canonical roadmap as part of
-- a composite planning kernel.  This module imports the auto-generated
-- canonical items and lifts them into a ``RoadmapAdapter``.  By
-- constructing a list of adapters and passing it to ``unifiedIndex`` you
-- obtain a single consolidated roadmap.  Additional adapters may be
-- appended to the ``planningAdapters`` list without modifying the
-- canonical source.  Note: this file is part of the local branch and is
-- not auto-generated.

module Plan.CIM.PlanningKernel where

open import Agda.Builtin.List using (List; []; _∷_)
open import Agda.Builtin.String using (String)

open import Plan.CIM.RoadmapIndex using (RoadmapItem; RoadmapAdapter; unifiedIndex)
open import Plan.CIM.CanonicalRoadmap using (canonicalItems)

------------------------------------------------------------------------
-- Local roadmap entries
------------------------------------------------------------------------

-- | Local tasks introduced in this branch (not part of the autogenerated
-- canonical roadmap).
definitionRoadmapItems : List RoadmapItem
definitionRoadmapItems =
  record
    { id         = "BUILD-JSON-DECOMPOSITION"
    ; title      = "Decompose large JSON artifacts via natural transformations"
    ; description = "Implement hierarchical decomposition of monolithic build JSONs (dependency_graph.json, canonical_enriched.json, etc.) using category-theoretic natural transformations. Preserve losslessness and structure while improving granularity, diffability, and parallel build efficiency."
    ; status     = "in-progress"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("src/agda/Plan/CIM/JSONTransformation.agda"
                    ∷ "scripts/json_decompose.py"
                    ∷ "scripts/json_recompose.py"
                    ∷ [])
    ; tags       = ("JSON" ∷ "NaturalTransformation" ∷ "SPPF" ∷ "Build" ∷ [])
    ; dependsOn  = []
    ; provenance = ("session: JSON decomposition design review (2026-01-04)" ∷ [])
    ; related    = ("BUILD-JSON-SCHEMA" ∷ "BUILD-JSON-HIERARCHY" ∷ [])
    }
  ∷
  record
    { id         = "BUILD-JSON-SCHEMA"
    ; title      = "Formalize JSON transformation schema in Agda"
    ; description = "Define record types for Monolithic and Hierarchical JSON representations, along with natural transformation laws. Prove isomorphism: backward ∘ forward ≡ id and structure preservation. Extended with adequacy framework: synthesize transformations from compositional primitives (json-get, json-set, json-merge) instead of monolithic Python FFI."
    ; status     = "in-progress"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("src/agda/Plan/CIM/JSONTransformation.agda"
                    ∷ "src/agda/Plan/CIM/JSONTransformationAdequacy.agda"
                    ∷ "src/agda/Plan/CIM/JSONTransformationProofs.agda"
                    ∷ [])
    ; tags       = ("JSON" ∷ "FormalizationProof" ∷ "CategoryTheory" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("BUILD-JSON-DECOMPOSITION" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-HIERARCHY"
    ; title      = "Design hierarchical JSON directory structure"
    ; description = "Document and implement the target hierarchy: dependency_graph → deps/, canonical_enriched → enriched/, planning_index → planning/ with _index.json manifests, metadata files, and aggregation rules."
    ; status     = "done"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("docs/process/JSON-DECOMPOSITION.md"
                    ∷ "build/schemas/hierarchy.md"
                    ∷ [])
    ; tags       = ("JSON" ∷ "Documentation" ∷ "Schema" ∷ [])
    ; dependsOn  = ("BUILD-JSON-DECOMPOSITION" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-FORWARD"
    ; title      = "Implement monolithic → hierarchical forward transformation"
    ; description = "Synthesize forward transformation from adequacy kit primitives (json-get, json-set, extractItems, generateIndexManifest). Kit provides decomposition strategy + primitive operations; adequacy proof witnesses sufficiency. Extract to Haskell/Python or implement primitives directly in Agda."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("scripts/json_decompose.py" ∷ [])
    ; tags       = ("JSON" ∷ "Implementation" ∷ "Python" ∷ [])
    ; dependsOn  = ("BUILD-JSON-SCHEMA" ∷ "BUILD-JSON-HIERARCHY" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-BACKWARD"
    ; title      = "Implement hierarchical → monolithic backward transformation"
    ; description = "Write inverse transformer that reconstructs original monolithic JSON from hierarchical fragments, with roundtrip verification for CI."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("scripts/json_recompose.py" ∷ [])
    ; tags       = ("JSON" ∷ "Implementation" ∷ "Python" ∷ [])
    ; dependsOn  = ("BUILD-JSON-FORWARD" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-APPLY-DEPS"
    ; title      = "Apply decomposition to dependency_graph.json"
    ; description = "First target: decompose 84-module dependency graph into build/deps/{modules,layers,cycles}/ hierarchy with module-level granularity."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("build/deps/_metadata.json"
                    ∷ "build/deps/modules/_index.json"
                    ∷ "build/deps/layers/_index.json"
                    ∷ [])
    ; tags       = ("JSON" ∷ "DependencyGraph" ∷ "Phase1" ∷ [])
    ; dependsOn  = ("BUILD-JSON-BACKWARD" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-APPLY-ENRICHED"
    ; title      = "Apply decomposition to canonical_enriched.json"
    ; description = "Second target: decompose roadmap enrichment data into build/enriched/{items,dependencies,annotations}/ with per-item granularity."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("build/enriched/_metadata.json"
                    ∷ "build/enriched/items/_index.json"
                    ∷ "build/enriched/dependencies/_manifest.json"
                    ∷ [])
    ; tags       = ("JSON" ∷ "RoadmapEnrichment" ∷ "Phase1" ∷ [])
    ; dependsOn  = ("BUILD-JSON-BACKWARD" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-APPLY-PLANNING"
    ; title      = "Apply decomposition to planning_index.json"
    ; description = "Third target: decompose planning index into build/planning/{items,sources,artifacts}/ with natural hierarchical layout."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("build/planning/_metadata.json"
                    ∷ "build/planning/items/_index.json"
                    ∷ "build/planning/sources/_manifest.json"
                    ∷ [])
    ; tags       = ("JSON" ∷ "PlanningIndex" ∷ "Phase1" ∷ [])
    ; dependsOn  = ("BUILD-JSON-BACKWARD" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-QUERY-LAYER"
    ; title      = "Implement query layer for hierarchical JSON"
    ; description = "Build Python/Agda utilities for querying decomposed JSON: by-category, by-module, transitive-deps, etc., using _index.json for efficient lookups without scanning filesystem."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("scripts/query_json_hierarchy.py"
                    ∷ "src/agda/Plan/CIM/JSONQuery.agda"
                    ∷ [])
    ; tags       = ("JSON" ∷ "Query" ∷ "Performance" ∷ [])
    ; dependsOn  = ("BUILD-JSON-APPLY-DEPS" ∷ "BUILD-JSON-APPLY-ENRICHED" ∷ "BUILD-JSON-APPLY-PLANNING" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "BUILD-JSON-VALIDATION"
    ; title      = "Implement CI validation for roundtrip equivalence"
    ; description = "Add Makefile target to validate: decompose → recompose yields original JSON bit-for-bit, ensuring losslessness."
    ; status     = "not-started"
    ; category   = "Build Infrastructure"
    ; source     = "JSONDecomposition"
    ; files      = ("scripts/validate_json_roundtrip.py" ∷ [])
    ; tags       = ("JSON" ∷ "CI" ∷ "Validation" ∷ [])
    ; dependsOn  = ("BUILD-JSON-BACKWARD" ∷ [])
    ; provenance = ("design review" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-DEF-DICT"
    ; title      = "Implement Definition Dictionary adequacy module"
    ; description = "Package the Definition Dictionary adequacy module so downstream proofs rely on a canonical definition space."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Definitions/Dictionary.agda" ∷ [])
    ; tags       = ("Definition" ∷ "Adequacy" ∷ [])
    ; dependsOn  = []
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR"
    ; title      = "Introduce generic functor interface for protocol bundles"
    ; description = "Establish the generic functor interface for protocol bundles so adapters share a single abstraction."
    ; status     = "in-progress"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Interface.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/Ambiguity.agda"
                    ∷ "src/agda/Infrastructure/Functor/Compose.agda"
                    ∷ "src/agda/Core/PhaseCategoryWrapper.agda"
                    ∷ [])
    ; tags       = ("Functor" ∷ "Interface" ∷ [])
    ; dependsOn  = ("LOCAL-DEF-DICT" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS"
    ; title      = "Complete generic functor interface laws and helpers"
    ; description = "Complete the generic functor interface laws and helpers to provide the coherence proofs downstream components expect."
    ; status     = "in-progress"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Interface" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTERFACE-CONVENIENCE-LAWS"
    ; title      = "Add convenience lemmas for map-id/compose congruence"
    ; description = "Add map-id and compose convenience lemmas so reasoning about the interface stays manageable."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Interface" ∷ "Law" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTERFACE-DOCUMENTATION"
    ; title      = "Document interface laws and usage in code comments"
    ; description = "Document the interface laws and usage so the new functor API stays discoverable."
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Documentation" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-DOCS" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION"
    ; title      = "Normalize existing functor instances onto shared interface"
    ; description = "Normalize existing functor instances onto the shared interface to keep implementations aligned."
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda"
                    ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-FUNCTION"
    ; title      = "Normalize FunctionCategory functor instance"
    ; description = "Align the FunctionCategory instance with the generic functor interface so generic algorithms see a consistent surface."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-FUNCPATH"
    ; title      = "Normalize FunctionPathCategory functor instance"
    ; description = "Normalize the FunctionPathCategory functor instance so path-based functors also obey the shared interface."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-TRANSFORMATION"
    ; title      = "Normalize TransformationSystem functor instance"
    ; description = "Normalize the TransformationSystem functor instance so rewriting follows the unified functor pattern."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-PATHALGEBRA"
    ; title      = "Normalize PathAlgebra functor instance"
    ; description = "Normalize the PathAlgebra functor instance so algebraic paths reuse the same categorical structure."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-PHASE"
    ; title      = "Normalize PhaseCategory functor instance"
    ; description = "Normalize the PhaseCategory functor instance so phases can be treated uniformly under the interface."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-NORMALIZE-AMBIGUITY"
    ; title      = "Normalize Ambiguity functor instance"
    ; description = "Normalize the Ambiguity functor instance so branching semantics align with the shared abstraction."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY"
    ; title      = "Ensure adequacy kits follow standardized pattern"
    ; description = "Ensure adequacy kits follow the standardized pattern so adequacy proofs stay consistent."
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-FUNCPATH"
    ; title      = "Confirm FunctionPath adequacy follows shared kit pattern"
    ; description = "Confirm FunctionPath adequacy follows the shared kit pattern to keep path-level correctness continuous."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-TRANSFORMATION"
    ; title      = "Confirm TransformationSystem adequacy follows shared kit pattern"
    ; description = "Confirm the TransformationSystem adequacy follows the shared kit pattern so rewrites stay sound."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-AMBIGUITY"
    ; title      = "Confirm Ambiguity adequacy follows shared kit pattern"
    ; description = "Confirm Ambiguity adequacy follows the shared kit pattern so alternative parses remain justified."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS"
    ; title      = "Align functor composition adapters with interface"
    ; description = "Build adapters so existing structures interoperate through the new generic functor interface."
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Compose.agda"
                    ∷ "src/agda/Core/PhaseCategoryWrapper.agda"
                    ∷ [])
    ; tags       = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTEROP-COMPOSE"
    ; title      = "Refine compose helper proofs for reuse"
    ; description = "Verify compose helper proofs so adapters retain interoperability when chained."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Compose.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTEROP-PHASE-WRAPPER"
    ; title      = "Ensure PhaseCategoryWrapper matches interface helpers"
    ; description = "Ensure the PhaseCategoryWrapper matches interface helpers so interoperable functors can be staged per phase."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Core/PhaseCategoryWrapper.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-EXAMPLES"
    ; title      = "Add regression examples exercising functor identity/compose"
    ; description = "Add regression examples to demonstrate how the generic functor interface simplifies identity and compose reasoning."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Examples/FunctorComposition.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Example" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-DOCS"
    ; title      = "Document generic functor interface and upgrade guide"
    ; description = "Document the generic functor interface and upgrade guide so contributors understand the migration path."
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("ROADMAP.md" ∷ "docs/process" ∷ [])
    ; tags       = ("Functor" ∷ "Documentation" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    }
  ∷
  record
    { id         = "DOCS-AGDA-DOCCOMMENT-PIPELINE"
    ; title      = "Extend module exporter to surface Agda doc comments"
    ; description = "Describe the doc-comment pipeline so Agda declarations stay annotated and downstream tools can export them."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "Documentation"
    ; files      = ("src/agda/Plan/CIM/ModuleExporter.agda" ∷ "docs/automation" ∷ [])
    ; tags       = ("Documentation" ∷ "Pipeline" ∷ "Agda" ∷ [])
    ; dependsOn  = []
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "DOCS-AGDA-DECL-DOCS"
    ; title      = "Export declaration docstrings (records/data) into docs"
    ; description = "Export declaration docstrings so records and data constructors carry human-readable intent."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "Documentation"
    ; files      = ("src/agda/Plan/CIM/ModuleExporter.agda" ∷ "docs/automation" ∷ [])
    ; tags       = ("Documentation" ∷ "Pipeline" ∷ "Agda" ∷ [])
    ; dependsOn  = ("DOCS-AGDA-DOCCOMMENT-PIPELINE" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "DOCS-AGDA-FIELD-DOCS"
    ; title      = "Export field/argument docstrings into docs"
    ; description = "Export field and argument docstrings so data carriers are explained in generated docs."
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "Documentation"
    ; files      = ("src/agda/Plan/CIM/ModuleExporter.agda" ∷ "docs/automation" ∷ [])
    ; tags       = ("Documentation" ∷ "Pipeline" ∷ "Agda" ∷ [])
    ; dependsOn  = ("DOCS-AGDA-DECL-DOCS" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "DOCS-AGDA-LINT"
    ; title      = "Add lint to enforce module-level docstrings"
    ; description = "Add lint that enforces module-level docstrings to maintain documentation coverage."
    ; status     = "in-progress"
    ; category   = "Infrastructure"
    ; source     = "Documentation"
    ; files      = ("scripts" ∷ "docs/automation" ∷ [])
    ; tags       = ("Documentation" ∷ "Lint" ∷ "Agda" ∷ [])
    ; dependsOn  = ("DOCS-AGDA-DOCCOMMENT-PIPELINE" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("DOCS-AGDA-DECL-DOCS" ∷ "DOCS-AGDA-FIELD-DOCS" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-FUNCPATH-ADEQUACY"
    ; title      = "Add adequacy kit for FunctionPathCategory"
    ; description = "Add an adequacy kit for FunctionPathCategory so path-level operations retain their invariants."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-TRANSFORMATION-ADEQUACY"
    ; title      = "Add adequacy hook for TransformationSystem functor"
    ; description = "Add an adequacy hook for the TransformationSystem functor so rewrites have constructive guarantees."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-AMBIGUITY-ADEQUACY"
    ; title      = "Add adequacy hook for Ambiguity functor"
    ; description = "Add an adequacy hook for the Ambiguity functor so divergent parses stay justified."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-DEF-DICT-EXAMPLE"
    ; title      = "Add DefinitionDictionary adequacy example"
    ; description = "Add a DefinitionDictionary adequacy example to document how adequacy proofs are structured."
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Examples/DefinitionDictionaryAdequacy.agda" ∷ [])
    ; tags       = ("Definition" ∷ "Example" ∷ [])
    ; dependsOn  = ("LOCAL-DEF-DICT" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    }
  ∷
  []

definitionAdapter : RoadmapAdapter
RoadmapAdapter.name definitionAdapter = "local-definition-dictionary"
RoadmapAdapter.items definitionAdapter = definitionRoadmapItems

------------------------------------------------------------------------
-- Canonical adapter
------------------------------------------------------------------------

-- | ``canonicalAdapter`` lifts the list of ``canonicalItems`` into a
-- ``RoadmapAdapter``.  The name identifies the origin of these items.
canonicalAdapter : RoadmapAdapter
RoadmapAdapter.name canonicalAdapter = "canonical-roadmap"
RoadmapAdapter.items canonicalAdapter = canonicalItems

------------------------------------------------------------------------
-- Planning adapters and unified index
------------------------------------------------------------------------

-- | ``planningAdapters`` collects all adapters that participate in the
-- planning kernel.  To extend the kernel with your own tasks, define
-- another adapter and cons it onto this list.  For example:
-- ``myAdapter ∷ planningAdapters``.
planningAdapters : List RoadmapAdapter
planningAdapters = definitionAdapter ∷ canonicalAdapter ∷ []

-- | ``planningIndex`` is the deduplicated list of ``RoadmapItem`` that
-- results from merging all adapters in ``planningAdapters``.  Use this
-- as the authoritative view of all tasks when performing introspective
-- planning.  See ``Plan.CIM.RoadmapIndex.unifiedIndex`` for details.
planningIndex : List RoadmapItem
planningIndex = unifiedIndex planningAdapters
