{-# OPTIONS --without-K #-}

-- | PlanningKernel: bridge module to expose the canonical roadmap as part of
-- a composite planning kernel.  This module imports the auto-generated
-- canonical items and lifts them into a ``RoadmapAdapter``.  By
-- constructing a list of adapters and passing it to ``unifiedIndex`` you
-- obtain a single consolidated roadmap.  Additional adapters may be
-- appended to the ``planningAdapters`` list without modifying the
-- canonical source.  Note: this file is part of the local branch and is
-- not auto-generated.

module Plan.CIM.PlanningKernel where

open import Agda.Builtin.List using (List; []; _∷_)
open import Agda.Builtin.String using (String)

open import Plan.CIM.RoadmapIndex using (RoadmapItem; RoadmapAdapter; unifiedIndex)
open import Plan.CIM.CanonicalRoadmap using (canonicalItems)

------------------------------------------------------------------------
-- Local roadmap entries
------------------------------------------------------------------------

-- | Local tasks introduced in this branch (not part of the autogenerated
-- canonical roadmap).
definitionRoadmapItems : List RoadmapItem
definitionRoadmapItems =
  record
    { id         = "LOCAL-DEF-DICT"
    ; title      = "Implement Definition Dictionary adequacy module"
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Definitions/Dictionary.agda" ∷ [])
    ; tags       = ("Definition" ∷ "Adequacy" ∷ [])
    ; dependsOn  = []
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR"
    ; title      = "Introduce generic functor interface for protocol bundles"
    ; status     = "in-progress"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Interface.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/Ambiguity.agda"
                    ∷ "src/agda/Infrastructure/Functor/Compose.agda"
                    ∷ "src/agda/Core/PhaseCategoryWrapper.agda"
                    ∷ [])
    ; tags       = ("Functor" ∷ "Interface" ∷ [])
    ; dependsOn  = ("LOCAL-DEF-DICT" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS"
    ; title      = "Complete generic functor interface laws and helpers"
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Interface.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Interface" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION"
    ; title      = "Normalize existing functor instances onto shared interface"
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PhaseCategory.agda"
                    ∷ "src/agda/Infrastructure/Functor/Instances/PathAlgebra.agda"
                    ∷ [])
    ; tags       = ("Functor" ∷ "Refactor" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-ADEQUACY-CONSISTENCY"
    ; title      = "Ensure adequacy kits follow standardized pattern"
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-INTEROP-ADAPTERS"
    ; title      = "Align functor composition adapters with interface"
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Compose.agda"
                    ∷ "src/agda/Core/PhaseCategoryWrapper.agda"
                    ∷ [])
    ; tags       = ("Functor" ∷ "Interop" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-EXAMPLES"
    ; title      = "Add regression examples exercising functor identity/compose"
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Examples/FunctorComposition.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Example" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INTERFACE-COMPLETENESS" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-DOCS"
    ; title      = "Document generic functor interface and upgrade guide"
    ; status     = "not-started"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("ROADMAP.md" ∷ "docs/process" ∷ [])
    ; tags       = ("Functor" ∷ "Documentation" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR-INSTANCE-NORMALIZATION" ∷ [])
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-FUNCPATH-ADEQUACY"
    ; title      = "Add adequacy kit for FunctionPathCategory"
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/FunctionPathCategory.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-TRANSFORMATION-ADEQUACY"
    ; title      = "Add adequacy hook for TransformationSystem functor"
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/TransformationSystem.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-GENERIC-FUNCTOR-AMBIGUITY-ADEQUACY"
    ; title      = "Add adequacy hook for Ambiguity functor"
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Infrastructure/Functor/Instances/Ambiguity.agda" ∷ [])
    ; tags       = ("Functor" ∷ "Adequacy" ∷ [])
    ; dependsOn  = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = []
    }
  ∷
  record
    { id         = "LOCAL-DEF-DICT-EXAMPLE"
    ; title      = "Add DefinitionDictionary adequacy example"
    ; status     = "done"
    ; category   = "Infrastructure"
    ; source     = "DefinitionDictionary"
    ; files      = ("src/agda/Examples/DefinitionDictionaryAdequacy.agda" ∷ [])
    ; tags       = ("Definition" ∷ "Example" ∷ [])
    ; dependsOn  = ("LOCAL-DEF-DICT" ∷ [])
    ; provenance = ("intake/codex_handoff.md" ∷ [])
    ; related    = ("LOCAL-GENERIC-FUNCTOR" ∷ [])
    }
  ∷
  []

definitionAdapter : RoadmapAdapter
RoadmapAdapter.name definitionAdapter = "local-definition-dictionary"
RoadmapAdapter.items definitionAdapter = definitionRoadmapItems

------------------------------------------------------------------------
-- Canonical adapter
------------------------------------------------------------------------

-- | ``canonicalAdapter`` lifts the list of ``canonicalItems`` into a
-- ``RoadmapAdapter``.  The name identifies the origin of these items.
canonicalAdapter : RoadmapAdapter
RoadmapAdapter.name canonicalAdapter = "canonical-roadmap"
RoadmapAdapter.items canonicalAdapter = canonicalItems

------------------------------------------------------------------------
-- Planning adapters and unified index
------------------------------------------------------------------------

-- | ``planningAdapters`` collects all adapters that participate in the
-- planning kernel.  To extend the kernel with your own tasks, define
-- another adapter and cons it onto this list.  For example:
-- ``myAdapter ∷ planningAdapters``.
planningAdapters : List RoadmapAdapter
planningAdapters = definitionAdapter ∷ canonicalAdapter ∷ []

-- | ``planningIndex`` is the deduplicated list of ``RoadmapItem`` that
-- results from merging all adapters in ``planningAdapters``.  Use this
-- as the authoritative view of all tasks when performing introspective
-- planning.  See ``Plan.CIM.RoadmapIndex.unifiedIndex`` for details.
planningIndex : List RoadmapItem
planningIndex = unifiedIndex planningAdapters
