{-# OPTIONS --without-K #-}

-- Algebra.Rings.BasicWithTheorems: Rings with explicit theorem sourcing
--
-- Refactored version of Algebra/Rings/Basic that makes theorem
-- dependencies explicit by importing from Theorems.Classical.

module Algebra.Rings.BasicWithTheorems where

open import Core
open import Chapter1.Level1Index
open import Chapter2.Level2sub3
open import Algebra.Foundation
open import Algebra.Groups.Basic
open import PropertyRegistry
open import Metamodel as M
open import Algebra.Rings.Theorems.Classical

-- ============================================================================
-- III.1: Rings and Homomorphisms
-- ============================================================================

-- Ring (from Foundation, but expanded here)
record RingDeclaration : Set₁ where
  field
    identifier : M.Identifier
    additiveGroup : AbelianGroupDeclaration
    multiplication : M.Identifier
    multAssociative : M.Identifier
    leftDistributive : M.Identifier
    rightDistributive : M.Identifier

-- Ring with unity (unital ring)
record UnitalRingDeclaration : Set₁ where
  field
    underlyingRing : RingDeclaration
    multiplicativeIdentity : M.Identifier
    leftIdentity : M.Identifier
    rightIdentity : M.Identifier

-- Commutative ring
record CommutativeRingDeclaration : Set₁ where
  field
    underlyingRing : UnitalRingDeclaration
    commutativity : M.Identifier

-- Division ring (skew field)
record DivisionRingDeclaration : Set₁ where
  field
    underlyingRing : UnitalRingDeclaration
    inverses : M.Identifier

-- Field (commutative division ring)
record FieldDeclaration : Set₁ where
  field
    underlyingRing : CommutativeRingDeclaration
    inverses : M.Identifier

-- Ring homomorphism
record RingHomomorphism (R S : RingDeclaration) : Set₁ where
  field
    sourceRing : RingDeclaration
    targetRing : RingDeclaration
    morphism : M.Identifier
    preservesAddition : M.Identifier
    preservesMultiplication : M.Identifier

-- Unital ring homomorphism (preserves 1)
record UnitalRingHomomorphism (R S : UnitalRingDeclaration) : Set₁ where
  field
    sourceRing : UnitalRingDeclaration
    targetRing : UnitalRingDeclaration
    underlyingHomomorphism : RingHomomorphism (UnitalRingDeclaration.underlyingRing sourceRing) (UnitalRingDeclaration.underlyingRing targetRing)
    preservesUnity : M.Identifier

-- Category of rings
record CategoryOfRings : Set₁ where
  field
    category : M.Identifier
    hasProducts : M.Identifier
    hasCoproducts : M.Identifier

-- Category of commutative rings
record CategoryOfCommutativeRings : Set₁ where
  field
    category : M.Identifier
    categoryOfRings : CategoryOfRings

-- ============================================================================
-- III.2: Ideals
-- ============================================================================

-- Left ideal
record LeftIdeal (R : RingDeclaration) : Set₁ where
  field
    ring : RingDeclaration
    additiveSubgroup : Subgroup (AbelianGroupDeclaration.underlyingGroup (RingDeclaration.additiveGroup ring))
    closedUnderLeftMultiplication : M.Identifier

-- Right ideal
record RightIdeal (R : RingDeclaration) : Set₁ where
  field
    ring : RingDeclaration
    additiveSubgroup : Subgroup (AbelianGroupDeclaration.underlyingGroup (RingDeclaration.additiveGroup ring))
    closedUnderRightMultiplication : M.Identifier

-- Two-sided ideal (ideal)
record Ideal (R : RingDeclaration) : Set₁ where
  field
    ring : RingDeclaration
    leftIdeal : LeftIdeal ring
    rightIdeal : RightIdeal ring

-- Principal ideal (generated by single element)
record PrincipalIdeal (R : RingDeclaration) (a : M.Identifier) : Set₁ where
  field
    ring : RingDeclaration
    generator : M.Identifier
    ideal : Ideal ring

-- Quotient ring (categorical quotient)
record QuotientRing (R : RingDeclaration) (I : Ideal R) : Set₁ where
  field
    ring : RingDeclaration
    ideal : Ideal ring
    quotientRing : RingDeclaration
    canonicalProjection : M.Identifier

-- First Isomorphism Theorem for rings
-- Sourced from module: ringFirstIsomorphismTheorem

-- Prime ideal (categorical perspective: reflects to prime spectrum)
record PrimeIdeal (R : CommutativeRingDeclaration) : Set₁ where
  field
    ring : CommutativeRingDeclaration
    ideal : Ideal (UnitalRingDeclaration.underlyingRing (CommutativeRingDeclaration.underlyingRing ring))
    isPrime : M.Identifier

-- Maximal ideal (categorical perspective: R/M is a field)
record MaximalIdeal (R : CommutativeRingDeclaration) : Set₁ where
  field
    ring : CommutativeRingDeclaration
    ideal : Ideal (UnitalRingDeclaration.underlyingRing (CommutativeRingDeclaration.underlyingRing ring))
    isMaximal : M.Identifier

-- Maximal implies prime in commutative rings
-- Sourced from module: maximalImpliesPrime

-- ============================================================================
-- III.3: Factorization in Commutative Rings
-- ============================================================================

-- Integral domain (commutative ring with no zero divisors)
record IntegralDomain : Set₁ where
  field
    underlyingRing : CommutativeRingDeclaration
    noZeroDivisors : M.Identifier

-- Unit (invertible element)
record Unit (R : UnitalRingDeclaration) (u : M.Identifier) : Set₁ where
  field
    ring : UnitalRingDeclaration
    element : M.Identifier
    multiplicativeInverse : M.Identifier

-- Associate elements
record Associates (R : IntegralDomain) (a b : M.Identifier) : Set₁ where
  field
    domain : IntegralDomain
    element1 : M.Identifier
    element2 : M.Identifier
    isAssociate : M.Identifier

-- Irreducible element
record IrreducibleElement (R : IntegralDomain) (p : M.Identifier) : Set₁ where
  field
    domain : IntegralDomain
    element : M.Identifier
    isIrreducible : M.Identifier

-- Prime element
record PrimeElement (R : IntegralDomain) (p : M.Identifier) : Set₁ where
  field
    domain : IntegralDomain
    element : M.Identifier
    isPrime : M.Identifier

-- Prime implies irreducible
-- Sourced from module: primeImplesIrreducible

-- Unique Factorization Domain (UFD)
record UFD : Set₁ where
  field
    domain : IntegralDomain
    uniqueFactorization : M.Identifier

-- In UFD, irreducible iff prime
-- Sourced from module: ufdIrreducibleIffPrime

-- Principal Ideal Domain (PID)
record PrincipalIdealDomain : Set₁ where
  field
    domain : IntegralDomain
    allIdealsPrincipal : M.Identifier

-- PID implies UFD
-- Sourced from module: pidImplesUfd

-- Euclidean Domain
record EuclideanDomain : Set₁ where
  field
    domain : IntegralDomain
    euclideanFunction : M.Identifier
    divisionAlgorithm : M.Identifier

-- Euclidean domain implies PID
-- Sourced from module: euclideanImpliesPid

-- Hierarchy: Euclidean ⊂ PID ⊂ UFD ⊂ Integral Domain
-- Sourced from module: factorizationHierarchy

-- ============================================================================
-- III.4: Rings of Quotients and Localization
-- ============================================================================

-- Multiplicative system (multiplicatively closed set)
record MultiplicativeSystem (R : CommutativeRingDeclaration) : Set₁ where
  field
    ring : CommutativeRingDeclaration
    subset : M.Identifier
    containsOne : M.Identifier
    closedUnderMultiplication : M.Identifier

-- Localization (ring of fractions)
record Localization (R : CommutativeRingDeclaration) (S : MultiplicativeSystem R) : Set₁ where
  field
    ring : CommutativeRingDeclaration
    multiplicativeSystem : MultiplicativeSystem ring
    localization : CommutativeRingDeclaration
    universalMap : M.Identifier

-- Localization at prime ideal
record LocalizationAtPrime (R : CommutativeRingDeclaration) (P : PrimeIdeal R) : Set₁ where
  field
    ring : CommutativeRingDeclaration
    primeIdeal : PrimeIdeal ring
    localization : CommutativeRingDeclaration

-- Field of fractions (localization at all nonzero elements)
record FieldOfFractions (R : IntegralDomain) : Set₁ where
  field
    domain : IntegralDomain
    fieldOfFractions : FieldDeclaration
    universalProperty : M.Identifier

-- ============================================================================
-- III.5: Polynomial Rings
-- ============================================================================

-- Polynomial ring R[x]
record PolynomialRing (R : CommutativeRingDeclaration) : Set₁ where
  field
    coefficientRing : CommutativeRingDeclaration
    polynomialRing : CommutativeRingDeclaration
    universalProperty : M.Identifier

-- Multivariate polynomials R[x₁,...,xₙ]
record MultivariatePolynomialRing (R : CommutativeRingDeclaration) (n : M.Identifier) : Set₁ where
  field
    coefficientRing : CommutativeRingDeclaration
    numberOfVariables : M.Identifier
    polynomialRing : CommutativeRingDeclaration

-- If R is integral domain, so is R[x]
-- Sourced from module: polynomialPreservesIntegralDomain

-- If R is UFD, so is R[x] (Gauss's lemma)
-- Sourced from module: polynomialPreservesUfd

-- ============================================================================
-- III.6: Factorization in Polynomial Rings
-- ============================================================================

-- Content of polynomial (gcd of coefficients)
record ContentOfPolynomial (R : UFD) (f : M.Identifier) : Set₁ where
  field
    ufd : UFD
    polynomial : M.Identifier
    content : M.Identifier

-- Primitive polynomial (content = 1)
record PrimitivePolynomial (R : UFD) (f : M.Identifier) : Set₁ where
  field
    ufd : UFD
    polynomial : M.Identifier
    isPrimitive : M.Identifier

-- Gauss's Lemma: product of primitive polynomials is primitive
-- Sourced from module: gaussLemma

-- Eisenstein's Criterion for irreducibility
-- Sourced from module: eisensteinCriterion

-- ============================================================================
-- Integration with Category Theory
-- ============================================================================

-- Rings form a category
-- Sourced from module: ringCategory

-- Commutative rings and Lawvere theories
-- Sourced from module: commutativeRingsAsLawvereTheory

-- Polynomial ring as free algebra
-- Sourced from module: polynomialRingFreeAlgebra

-- Localization as categorical localization
-- Sourced from module: localizationUniversalProperty

-- Spec(R) - prime spectrum (connects to algebraic geometry)
record PrimeSpectrum (R : CommutativeRingDeclaration) : Set₁ where
  field
    ring : CommutativeRingDeclaration
    spectrum : M.Identifier
    topology : M.Identifier

-- Connection to sheaves and schemes (advanced, for future)
-- Sourced from module: specFunctor

-- Quotient rings as cokernels (in CRing)
-- Sourced from module: quotientRingIsCokernel

-- Connection to modules (prepares for Ch IV)
-- Sourced from module: ringsAndModuleCategories
