#!/usr/bin/env python3
"""Export unified planning index to ROADMAP.md format.

Uses shared modules for composability:
- shared_data: load_planning_index()
- shared_yaml: dump_yaml()
"""

from pathlib import Path
from collections import defaultdict
from shared_data import load_planning_index, REPO_ROOT
from shared_yaml import dump_yaml

HEADER = """# Metacatagory Development Roadmap

## Overview

This roadmap is synthesized from the planning index in [PlanningKernel.agda](src/agda/Plan/CIM/PlanningKernel.agda).
Generated by `make roadmap-export-md` to keep it aligned with repository state.

## Status Snapshot

* Agda: 2.8.0 (project setting)
* Docs regenerated via make docs
* Deferred items tracked in DEFERRED-TRACKING.md

## How to Regenerate

```text
make roadmap-export-md
make md-lint
```

## Notes

This document is a projection from the planning kernel. To update:

1. Edit source items (e.g., canonical in src/agda/Plan/CIM/RoadmapIndex.agda or other adapters)
2. Run `make planning-index-json` to refresh build/planning_index.json
3. Run `make roadmap-export-md` to regenerate this file

"""

def export_markdown(output_path: Path):
    """Export planning index to ROADMAP.md."""
    canonical = load_planning_index()
    
    lines = [HEADER.strip(), ""]
    
    # Group by category
    by_category = defaultdict(list)
    for item in canonical:
        by_category[item["category"]].append(item)
    
    # Render each category
    for category in sorted(by_category.keys()):
        items = by_category[category]
        lines.append(f"## {category}")
        lines.append("")
        
        for item in items:
            # Build frontmatter metadata
            frontmatter = {
                'id': item['id'],
                'title': item['title'],
                'description': item['description'],
                'status': item['status'],
                'category': item['category']
            }
            
            if item['dependsOn']:
                frontmatter['dependencies'] = item['dependsOn']
            
            if item['tags']:
                frontmatter['tags'] = item['tags']
            
            if item['files']:
                frontmatter['files'] = item['files']
            
            # Generate YAML frontmatter block
            yaml_str = dump_yaml(frontmatter)
            lines.append("```yaml")
            lines.append(yaml_str.rstrip())
            lines.append("```")
            lines.append("")
            
            # Format: * **Title** — Description [status: X]
            lines.append(f"- **{item['title']}** — {item['description']} [status: {item['status']}]")

            if item['source']:
                lines.append(f"  Source: {item['source']}")
            
            if item['files']:
                files_str = ', '.join(f"`{f}`" for f in item['files'])
                lines.append(f"  Target: {files_str}")
            
            if item['tags']:
                tags_str = ', '.join(item['tags'])
                lines.append(f"  Tags: {tags_str}")
            
            if item['dependsOn']:
                deps_str = ', '.join(f"`{d}`" for d in item['dependsOn'])
                lines.append(f"  Depends on: {deps_str}")
            
            lines.append("")
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Exported {len(canonical)} items to {output_path}")

if __name__ == "__main__":
    export_markdown(REPO_ROOT / "ROADMAP.md")
