#!/usr/bin/env python3
"""
Normalize generated markdown files with markdownlint.

This ensures all Agda/Python-generated markdown files comply with
the project's markdown style guide.
"""

import subprocess
import sys
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.shared.markdown import parse_yaml_fenced_blocks
from scripts.shared.paths import REPORTS_DIR

# Files generated by Agda or Python that should be normalized
GENERATED_FILES = [
    Path("README.md"),
    Path("CONTRIBUTING.md"),
    Path("docs/NAVIGATION.md"),
    Path("docs/planning/ROADMAP.md"),
    Path("docs/status/DEFERRED-TRACKING.md"),
    Path("docs/status/deferred-items.md"),
    Path("docs/architecture/FRAMEWORK-INTEROPERABILITY.md"),
    REPORTS_DIR / "test-report.md",
]

def find_markdownlint() -> Path | None:
    """
    Locate markdownlint-cli2. Prefer local node_modules; fall back to PATH.

    Returning None lets callers bail out with a clear message instead of
    hanging on an interactive npx install prompt.
    """
    local_bin = REPO_ROOT / "node_modules" / ".bin" / "markdownlint-cli2"
    if local_bin.exists():
        return local_bin
    from shutil import which
    found = which("markdownlint-cli2")
    return Path(found) if found else None

def extract_frontmatter(content: str):
    """Parse all YAML code blocks and return list of dicts."""
    return parse_yaml_fenced_blocks(content, include_errors=True)

def normalize_markdown(filepath: Path) -> bool:
    """Run markdownlint --fix on a file."""
    if not filepath.exists():
        print(f"⚠️  Skipping {filepath} (does not exist)")
        return True

    before_content = filepath.read_text(encoding="utf-8")
    fm_before = extract_frontmatter(before_content)
    if any('__parse_error__' in fm for fm in fm_before):
        print(f"✗ Frontmatter parse error before lint in {filepath}")
        return False

    tool = find_markdownlint()
    if tool is None:
        print("✗ markdownlint-cli2 not found. Please run `make node-deps` first.")
        return False

    try:
        result = subprocess.run(
            [str(tool), "--fix", str(filepath)],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
        
        if result.returncode == 0:
            after_content = filepath.read_text(encoding="utf-8")
            fm_after = extract_frontmatter(after_content)

            if fm_before != fm_after:
                print(f"✗ Frontmatter changed by normalization in {filepath}")
                return False

            print(f"✓ Normalized {filepath}")
            return True
        else:
            print(f"✗ Failed to normalize {filepath}")
            print(result.stdout)
            print(result.stderr)
            return False
    except Exception as e:
        print(f"✗ Error normalizing {filepath}: {e}")
        return False

def main():
    """Normalize all generated markdown files."""
    print("Normalizing generated markdown files...")
    print()
    
    success_count = 0
    total_count = 0
    
    for file_path in GENERATED_FILES:
        total_count += 1
        abs_path = file_path if file_path.is_absolute() else REPO_ROOT / file_path
        if normalize_markdown(abs_path):
            success_count += 1
    
    print()
    print(f"Normalized {success_count}/{total_count} files")
    
    if success_count < total_count:
        sys.exit(1)

if __name__ == "__main__":
    main()
