-- | Axiom instance for pentagon/associahedron coherence.
module Infrastructure.Axiom.Instances.PentagonAssociahedron where

open import Agda.Primitive using (Level; _⊔_)
open import Agda.Builtin.Nat using (Nat)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Infrastructure.Arity.BinTree using (BinTree)
open import Infrastructure.Polytopes.Associahedron using (Path; _++_; ++-assoc; []; _∷_)
open import Infrastructure.Polytopes.Associahedron.Triangulation using (PentagonFan; pentagon-from-fan)
open import Infrastructure.Axiom.Adequacy using (PathAlgebra)
open import Infrastructure.Axiom.Instance using (AxiomInstance; FramedFace)
open import Infrastructure.Equality using (cong)

-- PathAlgebra instance for the associahedron path calculus.
PA-Assoc : ∀ {ℓ : Level} {A : Set ℓ} {n : Nat} → PathAlgebra {ℓ} {ℓ} (BinTree A n)
PA-Assoc {ℓ} {A} {n} = record
  { Path = Path {ℓ = ℓ} {A = A} {n = n}
  ; _++_ = _++_
  ; ++-assoc = ++-assoc
  ; id = λ {t} → []
  ; id-left  = λ {a} {b} (p : Path {A = A} {n = n} a b) → refl
  ; id-right = λ {a} {b} (p : Path {A = A} {n = n} a b) → idr p
  }
  where
    idr : ∀ {a b} (p : Path {A = A} {n = n} a b) → p ++ [] ≡ p
    idr [] = refl
    idr (s ∷ ps) = cong (λ q → s ∷ q) (idr ps)

-- AxiomInstance: the pentagon face is generated by a fan triangulation kit.
PentagonInstance
  : ∀ {ℓ : Level} {A : Set ℓ} {n : Nat}
  → AxiomInstance (PA-Assoc {A = A} {n = n})
-- | Build the pentagon coherence instance using associahedron triangulations.
PentagonInstance {ℓ} {A} {n} = record
  { Kit  = PentagonFan {ℓV = ℓ} {ℓP = ℓ} (Path {ℓ = ℓ} {A = A} {n = n}) _++_
  ; face = λ K →
      let open PentagonFan K in
      record { a = v0 ; b = v3 ; face = record { lhs = pShort ; rhs = pLong } }
  ; solve = λ K → pentagon-from-fan (++-assoc) K
  }
