module Infrastructure.Axiom.Instances.PentagonAssociahedron where

open import Agda.Primitive using (Level; _⊔_)
open import Agda.Builtin.Nat using (Nat)
open import Infrastructure.Arity.BinTree using (BinTree)
open import Infrastructure.Polytopes.Associahedron using (Path; _++_; ++-assoc)
open import Infrastructure.Polytopes.Associahedron.Triangulation using (PentagonFan; pentagon-from-fan)
open import Infrastructure.Axiom.Adequacy using (PathAlgebra)
open import Infrastructure.Axiom.Instance using (AxiomInstance; FramedFace)

-- PathAlgebra instance for the associahedron path calculus.
PA-Assoc : ∀ {ℓ : Level} {A : Set ℓ} {n : Nat} → PathAlgebra {ℓ} {ℓ} (BinTree A n)
PA-Assoc {ℓ} {A} {n} = record
  { Path = Path {ℓ = ℓ} {A = A} {n = n}
  ; _++_ = _++_
  ; ++-assoc = ++-assoc
  }

-- AxiomInstance: the pentagon face is generated by a fan triangulation kit.
PentagonInstance
  : ∀ {ℓ : Level} {A : Set ℓ} {n : Nat}
  → AxiomInstance (PA-Assoc {A = A} {n = n})
PentagonInstance {ℓ} {A} {n} = record
  { Kit  = PentagonFan {ℓV = ℓ} {ℓP = ℓ} (Path {ℓ = ℓ} {A = A} {n = n}) _++_
  ; face = λ K →
      let open PentagonFan K in
      record { a = v0 ; b = v3 ; face = record { lhs = pShort ; rhs = pLong } }
  ; solve = λ K → pentagon-from-fan (++-assoc) K
  }
