-- Examples.NumberField.Sqrt2: Demonstration of number field bundle usage
-- This example shows how to use the registry with IsNumberField evidence
-- to get specialized algorithms for Q(√2).

module Examples.NumberField.Sqrt2 where

open import Core
open import Algebra.Foundation
open import Algebra.Rings.Basic
open import Algebra.Fields.Basic
open import Core.AlgebraicAlgorithms
open import Core.Algorithms.Bundle
open import Core.Algorithms.NumberFields
open import Core.Algorithms.Registry
open import Metamodel as M
open import Agda.Builtin.List using (List)

-- ============================================================================
-- Q(√2) Number Field Construction
-- ============================================================================

-- Base field Q (rationals) - symbolic representation
postulate
  ℚ : FieldDeclaration
  ℚ-isNumberField : IsNumberField ℚ

-- Extension Q(√2)
postulate
  ℚ√2 : FieldDeclaration
  ℚ√2-isNumberField : IsNumberField ℚ√2

-- ============================================================================
-- Algorithm Bundle Lookup
-- ============================================================================

-- Method 1: Evidence-based dispatch to specialized number field bundle
algorithmsWithEvidence : AlgorithmBundle ℚ ℚ√2
algorithmsWithEvidence = lookupWithNumberFieldEvidence ℚ ℚ√2 ℚ-isNumberField ℚ√2-isNumberField

-- Method 2: Generic lookup (falls back to defaults)
algorithmsGeneric : AlgorithmBundle ℚ ℚ√2
algorithmsGeneric = lookupAlgorithmBundle ℚ ℚ√2

-- Method 3: Direct bundle construction (most explicit)
algorithmsDirect : AlgorithmBundle ℚ ℚ√2
algorithmsDirect = numberFieldBundle ℚ ℚ√2 ℚ-isNumberField ℚ√2-isNumberField

-- ============================================================================
-- Using the Bundle
-- ============================================================================

-- Extract individual algorithms
sqrt2MinPolyAlg : MinimalPolynomialAlgorithm ℚ ℚ√2
sqrt2MinPolyAlg = AlgorithmBundle.minimalPolynomialAlg algorithmsWithEvidence

sqrt2GaloisAlg : GaloisGroupAlgorithm ℚ ℚ√2
sqrt2GaloisAlg = AlgorithmBundle.galoisGroupAlg algorithmsWithEvidence

sqrt2ExtensionDegreeAlg : FieldExtensionDegreeAlgorithm ℚ ℚ√2
sqrt2ExtensionDegreeAlg = AlgorithmBundle.extensionDegreeAlg algorithmsWithEvidence

-- Compute extension degree of Q(√2)/Q
degreeQsqrt2 : ExtensionDegree ℚ ℚ√2
degreeQsqrt2 = FieldExtensionDegreeAlgorithm.extensionDegree sqrt2ExtensionDegreeAlg

-- Get a basis for Q(√2)/Q (expected: {1, √2})
basisQsqrt2 : List M.Identifier
basisQsqrt2 = FieldExtensionDegreeAlgorithm.basis sqrt2ExtensionDegreeAlg

-- Compute Galois group of Q(√2)/Q
-- Expected: cyclic group of order 2 (generated by σ: √2 ↦ -√2)
galQsqrt2 : GaloisGroup ℚ ℚ√2
galQsqrt2 = GaloisGroupAlgorithm.galoisGroup sqrt2GaloisAlg (M.mkId "x²-2")

-- Check if √2 is algebraic over Q (yes, with minimal polynomial x² - 2)
sqrt2Algebraic : Dec (AlgebraicElement ℚ ℚ√2 (M.mkId "√2"))
sqrt2Algebraic = MinimalPolynomialAlgorithm.isAlgebraic sqrt2MinPolyAlg (M.mkId "√2")

-- ============================================================================
-- Verification Marker
-- ============================================================================

-- If this typechecks, evidence-based dispatch is working
exampleComplete : M.Identifier
exampleComplete = M.mkId "✓ Q(√2) example demonstrates evidence-based registry dispatch"
