{-# OPTIONS --without-K #-}

-- Algebra.Groups.Basic: Fundamental group theory (Hungerford Ch I, sections 1-6)
-- This module covers semigroups through symmetric groups, grounded in category theory.

module Algebra.Groups.Basic where

open import Core
open import Chapter1.Level1Index
open import Algebra.Foundation
open import PropertyRegistry
open import Metamodel as M

-- ============================================================================
-- I.1: Semigroups, Monoids and Groups
-- ============================================================================

-- Subgroup (categorical: subobject in Grp)
record Subgroup (G : GroupDeclaration) : Set₁ where
  field
    subset : M.Identifier
    inclusion : M.Identifier  -- H ↪ G (monic in Grp)
    closedUnderOp : M.Identifier
    containsIdentity : M.Identifier
    closedUnderInverse : M.Identifier

-- ============================================================================
-- I.2: Homomorphisms and Subgroups
-- ============================================================================

-- Image of a homomorphism (categorical: image factorization)
record ImageOfHomomorphism (f : M.Identifier) : Set₁ where
  field
    sourceGroup : GroupDeclaration
    targetGroup : GroupDeclaration
    homomorphism : GroupHomomorphism sourceGroup targetGroup
    -- im(f) = {f(g) | g ∈ G} ⊆ H
    imageSubgroup : Subgroup targetGroup
    factorization : M.Identifier  -- f = inclusion ∘ surjection

-- Kernel of homomorphism (categorical: kernel in abelian categories when applicable)
record KernelOfHomomorphism (f : M.Identifier) : Set₁ where
  field
    sourceGroup : GroupDeclaration
    targetGroup : GroupDeclaration
    homomorphism : GroupHomomorphism sourceGroup targetGroup
    -- ker(f) = {g ∈ G | f(g) = e_H}
    kernelSubgroup : Subgroup sourceGroup
    isKernel : M.Identifier

-- ============================================================================
-- I.3: Cyclic Groups
-- ============================================================================

-- Cyclic group generated by one element
record CyclicGroup : Set₁ where
  field
    underlyingGroup : GroupDeclaration
    generator : M.Identifier
    -- G = ⟨g⟩ = {gⁿ | n ∈ ℤ}
    isCyclic : M.Identifier

-- Order of an element
record ElementOrder (g : M.Identifier) (G : GroupDeclaration) : Set₁ where
  field
    element : M.Identifier
    -- ord(g) = min{n > 0 | gⁿ = e}, or ∞
    order : M.Identifier

-- Classification of cyclic groups (integration point: this connects to ℤ and ℤ/nℤ)
postulate
  CyclicGroup-Classification : 
    (G : CyclicGroup) → 
    M.Identifier  -- G ≅ ℤ or G ≅ ℤ/nℤ for some n

-- ============================================================================
-- I.4: Cosets and Counting (Lagrange's Theorem)
-- ============================================================================

-- Left coset
record LeftCoset (G : GroupDeclaration) (H : Subgroup G) (g : M.Identifier) : Set₁ where
  field
    subgroup : Subgroup G
    element : M.Identifier
    -- gH = {gh | h ∈ H}
    cosetSet : M.Identifier

-- Index of a subgroup
record IndexOfSubgroup (G : GroupDeclaration) (H : Subgroup G) : Set₁ where
  field
    group : GroupDeclaration
    subgroup : Subgroup group
    -- [G:H] = number of left cosets of H in G
    index : M.Identifier

-- Lagrange's Theorem: |G| = |H| · [G:H]
postulate
  Lagrange-Theorem :
    (G : GroupDeclaration) →
    (H : Subgroup G) →
    M.Identifier  -- |G| = |H| · [G:H]

-- ============================================================================
-- I.5: Normality, Quotient Groups, and Homomorphisms
-- ============================================================================

-- Normal subgroup (categorical: kernel of some homomorphism)
record NormalSubgroup (G : GroupDeclaration) : Set₁ where
  field
    subgroup : Subgroup G
    -- N ⊴ G iff gNg⁻¹ = N for all g ∈ G
    isNormal : M.Identifier

-- Quotient group (categorical: cokernel/quotient object)
record QuotientGroup (G : GroupDeclaration) (N : NormalSubgroup G) : Set₁ where
  field
    numeratorGroup : GroupDeclaration
    normalSubgroup : NormalSubgroup numeratorGroup
    -- G/N with operation (gN)(hN) = (gh)N
    quotientGroup : GroupDeclaration
    canonicalProjection : M.Identifier  -- π : G → G/N

-- First Isomorphism Theorem (categorical: factorization through image)
postulate
  First-Isomorphism-Theorem :
    (f : M.Identifier) →  -- Homomorphism G → H
    M.Identifier  -- G/ker(f) ≅ im(f)

-- Second Isomorphism Theorem
postulate
  Second-Isomorphism-Theorem :
    (G : GroupDeclaration) →
    (H : Subgroup G) →
    (N : NormalSubgroup G) →
    M.Identifier  -- H/(H ∩ N) ≅ HN/N

-- Third Isomorphism Theorem (categorical: quotient of quotient)
postulate
  Third-Isomorphism-Theorem :
    (G : GroupDeclaration) →
    (H N : NormalSubgroup G) →
    M.Identifier  -- (G/H)/(N/H) ≅ G/N when H ⊆ N

-- ============================================================================
-- I.6: Symmetric, Alternating, and Dihedral Groups
-- ============================================================================

-- Symmetric group Sₙ (permutations of n elements)
record SymmetricGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier  -- n
    -- Sₙ = group of bijections {1,...,n} → {1,...,n}
    underlyingGroup : GroupDeclaration
    -- |Sₙ| = n!
    order : M.Identifier

-- Cycle notation for permutations
record Cycle : Set₁ where
  field
    elements : M.Identifier
    -- (a₁ a₂ ... aₖ) sends aᵢ ↦ aᵢ₊₁ (cyclically)
    cycleStructure : M.Identifier

-- Sign of a permutation
record SignOfPermutation (n : M.Identifier) (σ : M.Identifier) : Set₁ where
  field
    permutation : M.Identifier
    symmetricGroup : SymmetricGroup n
    -- sgn(σ) ∈ {±1}, multiplicative
    sign : M.Identifier

-- Alternating group Aₙ (even permutations)
record AlternatingGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier
    symmetricGroup : SymmetricGroup degree
    -- Aₙ = ker(sgn : Sₙ → {±1})
    underlyingGroup : GroupDeclaration
    kernelOfSign : M.Identifier
    -- |Aₙ| = n!/2
    order : M.Identifier

-- Simplicity of Aₙ for n ≥ 5 (fundamental result)
postulate
  Alternating-Is-Simple :
    (n : M.Identifier) →
    M.Identifier  -- n ≥ 5 → Aₙ is simple (no proper normal subgroups)

-- Dihedral group Dₙ (symmetries of regular n-gon)
record DihedralGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier
    -- Dₙ = ⟨r, s | rⁿ = s² = e, srs = r⁻¹⟩
    underlyingGroup : GroupDeclaration
    rotation : M.Identifier  -- r
    reflection : M.Identifier  -- s
    -- |Dₙ| = 2n
    order : M.Identifier

-- ============================================================================
-- Integration Points with Category Theory
-- ============================================================================

-- Groups form a category (from Foundation)
-- Grp has:
-- - Objects: groups
-- - Morphisms: group homomorphisms
-- - Composition: function composition
-- - Identity: identity map

-- Normal subgroups are kernels (categorical perspective)
postulate
  NormalSubgroup-Is-Kernel :
    (G : GroupDeclaration) →
    (N : NormalSubgroup G) →
    M.Identifier  -- ∃ f : G → H such that N = ker(f)

-- Quotient groups are cokernels in abelian setting
postulate
  QuotientGroup-Is-Cokernel-In-Ab :
    (G : AbelianGroupDeclaration) →
    (N : NormalSubgroup (AbelianGroupDeclaration.underlyingGroup G)) →
    M.Identifier  -- G/N is cokernel in Ab

-- Isomorphism theorems reflect categorical factorization
-- First: G → G/ker(f) → im(f) ↪ H
-- Second: Diamond isomorphism in lattice of subgroups
-- Third: Quotients compose

-- ============================================================================
-- Connection to Lawvere Theories (for next module)
-- ============================================================================

-- Groups are models of the Lawvere theory of groups
-- This will be developed in the bridge to Chapter2.Level2sub3
postulate
  Groups-As-Lawvere-Models : M.Identifier

-- The category of groups has a free-forgetful adjunction
-- Free : Set → Grp ⊣ Forget : Grp → Set
-- This connects to Chapter I.7-9 on free groups
postulate
  Free-Forgetful-Adjunction-Grp : M.Identifier
