{-# OPTIONS --without-K #-}

-- Algebra.Groups.BasicWithTheorems: Groups/Basic with explicit theorem sourcing
--
-- This is a refactored version of Algebra/Groups/Basic that makes theorem
-- dependencies explicit by importing them from a theorem package rather than
-- postulating them locally.
--
-- To use this module, clients import:
--   open import Algebra.Groups.TheoremsClassical
--   open import Algebra.Groups.BasicWithTheorems
--
-- This architecture enables:
-- 1. Multiple theorem implementations (Classical, Categorical, Constructive)
-- 2. Clear separation of structure (definitions, records) from theorems
-- 3. Modular theorem development without scattering proofs
-- 4. Exploration of different mathematical frameworks

module Algebra.Groups.BasicWithTheorems where

open import Core
open import Chapter1.Level1Index
open import Algebra.Foundation
open import PropertyRegistry
open import Metamodel as M
open import Algebra.Groups.Theorems.Classical
open import Algebra.Groups.Types public

-- ============================================================================
-- I.1: Semigroups, Monoids and Groups
-- ============================================================================

-- Subgroup (categorical: subobject in Grp)
-- (Re-exported from Algebra.Groups.Types)

-- ============================================================================
-- I.2: Homomorphisms and Subgroups
-- ============================================================================

-- Image of a homomorphism (categorical: image factorization)
-- (Re-exported from Algebra.Groups.Types)

-- Kernel of homomorphism (categorical: kernel in abelian categories when applicable)
-- (Re-exported from Algebra.Groups.Types)

-- ============================================================================
-- I.3: Cyclic Groups
-- ============================================================================

-- Cyclic group generated by one element
-- (Re-exported from Algebra.Groups.Types)

-- Order of an element
-- (Re-exported from Algebra.Groups.Types)

-- Classification of cyclic groups (sourced from TheoremsClassical)
-- Exported from module: cyclicGroupClassification

-- ============================================================================
-- I.4: Cosets and Counting (Lagrange's Theorem)
-- ============================================================================

-- Left coset
-- (Re-exported from Algebra.Groups.Types)

-- Index of a subgroup
-- (Re-exported from Algebra.Groups.Types)

-- Lagrange's Theorem: |G| = |H| · [G:H]
-- Sourced from module: lagrangeTheorem

-- ============================================================================
-- I.5: Normality, Quotient Groups, and Homomorphisms
-- ============================================================================

-- Normal subgroup (categorical: kernel of some homomorphism)
-- (Re-exported from Algebra.Groups.Types)

-- Quotient group (categorical: cokernel/quotient object)
-- (Re-exported from Algebra.Groups.Types)

-- Isomorphism theorems sourced from module:
-- firstIsomorphismTheorem, secondIsomorphismTheorem, thirdIsomorphismTheorem

-- ============================================================================
-- I.6: Symmetric, Alternating, and Dihedral Groups
-- ============================================================================

-- Symmetric group Sₙ (permutations of n elements)
-- (Re-exported from Algebra.Groups.Types)

-- Cycle notation for permutations
-- (Re-exported from Algebra.Groups.Types)

-- Sign of a permutation
-- (Re-exported from Algebra.Groups.Types)

-- Alternating group Aₙ (even permutations)
-- (Re-exported from Algebra.Groups.Types)

-- Simplicity of Aₙ for n ≥ 5 (fundamental result)
-- Sourced from module: alternatingIsSimple

-- Dihedral group Dₙ (symmetries of regular n-gon)
-- (Re-exported from Algebra.Groups.Types)

-- ============================================================================
-- Integration Points with Category Theory
-- ============================================================================

-- Groups form a category (from Foundation)
-- Grp has:
-- - Objects: groups
-- - Morphisms: group homomorphisms
-- - Composition: function composition
-- - Identity: identity map

-- Normal subgroups are kernels (categorical perspective)
-- Sourced from module: normalSubgroupIsKernel

-- Quotient groups are cokernels in abelian setting
-- Sourced from module: quotientGroupIsCokernelInAb

-- Isomorphism theorems reflect categorical factorization
-- First: G → G/ker(f) → im(f) ↪ H
-- Second: Diamond isomorphism in lattice of subgroups
-- Third: Quotients compose

-- ============================================================================
-- Connection to Lawvere Theories (for next module)
-- ============================================================================

-- Groups are models of the Lawvere theory of groups
-- This will be developed in the bridge to Chapter2.Level2sub3
-- Sourced from module: groupsAsLawvereModels

-- The category of groups has a free-forgetful adjunction
-- Free : Set → Grp ⊣ Forget : Grp → Set
-- This connects to Chapter I.7-9 on free groups
-- Sourced from module: freeForgetfulAdjunctionGrp
