{-# OPTIONS --without-K #-}

-- Algebra.Groups.BasicWithTheorems: Groups/Basic with explicit theorem sourcing
--
-- This is a refactored version of Algebra/Groups/Basic that makes theorem
-- dependencies explicit by importing them from a theorem package rather than
-- postulating them locally.
--
-- To use this module, clients import:
--   open import Algebra.Groups.TheoremsClassical
--   open import Algebra.Groups.BasicWithTheorems
--
-- This architecture enables:
-- 1. Multiple theorem implementations (Classical, Categorical, Constructive)
-- 2. Clear separation of structure (definitions, records) from theorems
-- 3. Modular theorem development without scattering proofs
-- 4. Exploration of different mathematical frameworks

module Algebra.Groups.BasicWithTheorems where

open import Core
open import Chapter1.Level1Index
open import Algebra.Foundation
open import PropertyRegistry
open import Metamodel as M
open import Algebra.Groups.Theorems.Classical

-- ============================================================================
-- I.1: Semigroups, Monoids and Groups
-- ============================================================================

-- Subgroup (categorical: subobject in Grp)
record Subgroup (G : GroupDeclaration) : Set₁ where
  field
    subset : M.Identifier
    inclusion : M.Identifier  -- H ↪ G (monic in Grp)
    closedUnderOp : M.Identifier
    containsIdentity : M.Identifier
    closedUnderInverse : M.Identifier

-- ============================================================================
-- I.2: Homomorphisms and Subgroups
-- ============================================================================

-- Image of a homomorphism (categorical: image factorization)
record ImageOfHomomorphism (f : M.Identifier) : Set₁ where
  field
    sourceGroup : GroupDeclaration
    targetGroup : GroupDeclaration
    homomorphism : GroupHomomorphism sourceGroup targetGroup
    -- im(f) = {f(g) | g ∈ G} ⊆ H
    imageSubgroup : Subgroup targetGroup
    factorization : M.Identifier  -- f = inclusion ∘ surjection

-- Kernel of homomorphism (categorical: kernel in abelian categories when applicable)
record KernelOfHomomorphism (f : M.Identifier) : Set₁ where
  field
    sourceGroup : GroupDeclaration
    targetGroup : GroupDeclaration
    homomorphism : GroupHomomorphism sourceGroup targetGroup
    -- ker(f) = {g ∈ G | f(g) = e_H}
    kernelSubgroup : Subgroup sourceGroup
    isKernel : M.Identifier

-- ============================================================================
-- I.3: Cyclic Groups
-- ============================================================================

-- Cyclic group generated by one element
record CyclicGroup : Set₁ where
  field
    underlyingGroup : GroupDeclaration
    generator : M.Identifier
    -- G = ⟨g⟩ = {gⁿ | n ∈ ℤ}
    isCyclic : M.Identifier

-- Order of an element
record ElementOrder (g : M.Identifier) (G : GroupDeclaration) : Set₁ where
  field
    element : M.Identifier
    -- ord(g) = min{n > 0 | gⁿ = e}, or ∞
    order : M.Identifier

-- Classification of cyclic groups (sourced from TheoremsClassical)
-- Exported from module: cyclicGroupClassification

-- ============================================================================
-- I.4: Cosets and Counting (Lagrange's Theorem)
-- ============================================================================

-- Left coset
record LeftCoset (G : GroupDeclaration) (H : Subgroup G) (g : M.Identifier) : Set₁ where
  field
    subgroup : Subgroup G
    element : M.Identifier
    -- gH = {gh | h ∈ H}
    cosetSet : M.Identifier

-- Index of a subgroup
record IndexOfSubgroup (G : GroupDeclaration) (H : Subgroup G) : Set₁ where
  field
    group : GroupDeclaration
    subgroup : Subgroup group
    -- [G:H] = number of left cosets of H in G
    index : M.Identifier

-- Lagrange's Theorem: |G| = |H| · [G:H]
-- Sourced from module: lagrangeTheorem

-- ============================================================================
-- I.5: Normality, Quotient Groups, and Homomorphisms
-- ============================================================================

-- Normal subgroup (categorical: kernel of some homomorphism)
record NormalSubgroup (G : GroupDeclaration) : Set₁ where
  field
    subgroup : Subgroup G
    -- N ⊴ G iff gNg⁻¹ = N for all g ∈ G
    isNormal : M.Identifier

-- Quotient group (categorical: cokernel/quotient object)
record QuotientGroup (G : GroupDeclaration) (N : NormalSubgroup G) : Set₁ where
  field
    numeratorGroup : GroupDeclaration
    normalSubgroup : NormalSubgroup numeratorGroup
    -- G/N with operation (gN)(hN) = (gh)N
    quotientGroup : GroupDeclaration
    canonicalProjection : M.Identifier  -- π : G → G/N

-- Isomorphism theorems sourced from module:
-- firstIsomorphismTheorem, secondIsomorphismTheorem, thirdIsomorphismTheorem

-- ============================================================================
-- I.6: Symmetric, Alternating, and Dihedral Groups
-- ============================================================================

-- Symmetric group Sₙ (permutations of n elements)
record SymmetricGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier  -- n
    -- Sₙ = group of bijections {1,...,n} → {1,...,n}
    underlyingGroup : GroupDeclaration
    -- |Sₙ| = n!
    order : M.Identifier

-- Cycle notation for permutations
record Cycle : Set₁ where
  field
    elements : M.Identifier
    -- (a₁ a₂ ... aₖ) sends aᵢ ↦ aᵢ₊₁ (cyclically)
    cycleStructure : M.Identifier

-- Sign of a permutation
record SignOfPermutation (n : M.Identifier) (σ : M.Identifier) : Set₁ where
  field
    permutation : M.Identifier
    symmetricGroup : SymmetricGroup n
    -- sgn(σ) ∈ {±1}, multiplicative
    sign : M.Identifier

-- Alternating group Aₙ (even permutations)
record AlternatingGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier
    symmetricGroup : SymmetricGroup degree
    -- Aₙ = ker(sgn : Sₙ → {±1})
    underlyingGroup : GroupDeclaration
    kernelOfSign : M.Identifier
    -- |Aₙ| = n!/2
    order : M.Identifier

-- Simplicity of Aₙ for n ≥ 5 (fundamental result)
-- Sourced from module: alternatingIsSimple

-- Dihedral group Dₙ (symmetries of regular n-gon)
record DihedralGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier
    -- Dₙ = ⟨r, s | rⁿ = s² = e, srs = r⁻¹⟩
    underlyingGroup : GroupDeclaration
    rotation : M.Identifier  -- r
    reflection : M.Identifier  -- s
    -- |Dₙ| = 2n
    order : M.Identifier

-- ============================================================================
-- Integration Points with Category Theory
-- ============================================================================

-- Groups form a category (from Foundation)
-- Grp has:
-- - Objects: groups
-- - Morphisms: group homomorphisms
-- - Composition: function composition
-- - Identity: identity map

-- Normal subgroups are kernels (categorical perspective)
-- Sourced from module: normalSubgroupIsKernel

-- Quotient groups are cokernels in abelian setting
-- Sourced from module: quotientGroupIsCokernelInAb

-- Isomorphism theorems reflect categorical factorization
-- First: G → G/ker(f) → im(f) ↪ H
-- Second: Diamond isomorphism in lattice of subgroups
-- Third: Quotients compose

-- ============================================================================
-- Connection to Lawvere Theories (for next module)
-- ============================================================================

-- Groups are models of the Lawvere theory of groups
-- This will be developed in the bridge to Chapter2.Level2sub3
-- Sourced from module: groupsAsLawvereModels

-- The category of groups has a free-forgetful adjunction
-- Free : Set → Grp ⊣ Forget : Grp → Set
-- This connects to Chapter I.7-9 on free groups
-- Sourced from module: freeForgetfulAdjunctionGrp
