{-# OPTIONS --without-K #-}

module Algebra.Groups.Types where

-- Algebra.Groups.Types: Type definitions for group theory
-- This module exports all record types used in Algebra.Groups, allowing
-- these types to be used in parameter signatures for parameterized modules.

open import Core
open import Algebra.Foundation
open import Metamodel as M

-- ============================================================================
-- Basic Group Structures
-- ============================================================================

-- Subgroup (categorical: subobject in Grp)
record Subgroup (G : GroupDeclaration) : Set₁ where
  field
    subset : M.Identifier
    inclusion : M.Identifier  -- H ↪ G (monic in Grp)
    closedUnderOp : M.Identifier
    containsIdentity : M.Identifier
    closedUnderInverse : M.Identifier

-- Cyclic group generated by one element
record CyclicGroup : Set₁ where
  field
    underlyingGroup : GroupDeclaration
    generator : M.Identifier
    isCyclic : M.Identifier

-- Normal subgroup (categorical: kernel of some homomorphism)
record NormalSubgroup (G : GroupDeclaration) : Set₁ where
  field
    subgroup : Subgroup G
    -- N ⊴ G iff gNg⁻¹ = N for all g ∈ G
    isNormal : M.Identifier

-- ============================================================================
-- Homomorphism-Related Structures
-- ============================================================================

-- Image of a homomorphism (categorical: image factorization)
record ImageOfHomomorphism (f : M.Identifier) : Set₁ where
  field
    sourceGroup : GroupDeclaration
    targetGroup : GroupDeclaration
    homomorphism : GroupHomomorphism sourceGroup targetGroup
    imageSubgroup : Subgroup targetGroup
    factorization : M.Identifier  -- f = inclusion ∘ surjection

-- Kernel of homomorphism (categorical: kernel in abelian categories when applicable)
record KernelOfHomomorphism (f : M.Identifier) : Set₁ where
  field
    sourceGroup : GroupDeclaration
    targetGroup : GroupDeclaration
    homomorphism : GroupHomomorphism sourceGroup targetGroup
    kernelSubgroup : Subgroup sourceGroup
    isKernel : M.Identifier

-- ============================================================================
-- Element and Quotient Structures
-- ============================================================================

-- Order of an element
record ElementOrder (g : M.Identifier) (G : GroupDeclaration) : Set₁ where
  field
    element : M.Identifier
    order : M.Identifier

-- Left coset
record LeftCoset (G : GroupDeclaration) (H : Subgroup G) (g : M.Identifier) : Set₁ where
  field
    subgroup : Subgroup G
    element : M.Identifier
    cosetSet : M.Identifier

-- Index of a subgroup
record IndexOfSubgroup (G : GroupDeclaration) (H : Subgroup G) : Set₁ where
  field
    group : GroupDeclaration
    subgroup : Subgroup group
    index : M.Identifier

-- Quotient group (categorical: cokernel/quotient object)
record QuotientGroup (G : GroupDeclaration) (N : NormalSubgroup G) : Set₁ where
  field
    numeratorGroup : GroupDeclaration
    normalSubgroup : NormalSubgroup numeratorGroup
    quotientGroup : GroupDeclaration
    canonicalProjection : M.Identifier  -- π : G → G/N

-- ============================================================================
-- Permutation Groups
-- ============================================================================

-- Symmetric group Sₙ (permutations of n elements)
record SymmetricGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier  -- n
    underlyingGroup : GroupDeclaration
    order : M.Identifier

-- Cycle notation for permutations
record Cycle : Set₁ where
  field
    elements : M.Identifier
    cycleStructure : M.Identifier

-- Sign of a permutation
record SignOfPermutation (n : M.Identifier) (σ : M.Identifier) : Set₁ where
  field
    permutation : M.Identifier
    symmetricGroup : SymmetricGroup n
    sign : M.Identifier

-- Alternating group Aₙ (even permutations)
record AlternatingGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier
    symmetricGroup : SymmetricGroup degree
    underlyingGroup : GroupDeclaration
    kernelOfSign : M.Identifier
    order : M.Identifier

-- Dihedral group Dₙ (symmetries of regular n-gon)
record DihedralGroup (n : M.Identifier) : Set₁ where
  field
    degree : M.Identifier
    underlyingGroup : GroupDeclaration
    rotation : M.Identifier  -- r
    reflection : M.Identifier  -- s
    order : M.Identifier
